name: Deploy
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Prerequisites
        run: | 
          sudo apt install wireguard

      - name: Setup Connection
        uses: niklaskeerl/easy-wireguard-action@v2
        with:
          WG_CONFIG_FILE: ${{ vars.WG_CONFIG_FILE }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
      
          echo "${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}" > ~/.ssh/deployer
          chmod 600 ~/.ssh/deployer
          echo ${{ vars.DEPLOYER_PUBLIC_KEY }} > ~/.ssh/deployer.pub
          
          cat > ~/.ssh/config << 'EOF'
          Host vps
            HostName 10.8.0.1
            User deployer
            IdentityFile ~/.ssh/deployer
            IdentitiesOnly yes
            StrictHostKeyChecking accept-new
          EOF
      
          chmod 600 ~/.ssh/config
          
      - name: Test SSH
        run: |
          eval "$(ssh-agent -s)"
          echo ${{ secrets.DEPLOYER_SSH_PASSPHRASE }} | ssh-add ~/.ssh/deployer
          ssh -vvv vps 'whoami && hostname'

      - name: Connect to server, download changes and restart
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VPS_HOST_IP }}
          username: ${{ secrets.DEPLOYER_USERNAME }}
          password: ${{ secrets.DEPLOYER_PASS }}
          key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          passphrase: ${{ secrets.DEPLOYER_SSH_PASSPHRASE }}
          script: |
            eval "$(ssh-agent -s)"
            echo ${{ secrets.DEPLOYER_SSH_PASSPHRASE }} | ssh-add ~/.ssh/deployer
            if [ -d liferay-portal-sample ]; then
              cd ~/liferay-portal-sample
              git pull --rebase -Xours
              docker compose -f liferay-portal-sample/configs/prod/docker-compose.yml down
              docker compose -f liferay-portal-sample/configs/prod/docker-compose.yml up
            else
              git clone git@github.com:codeboychik/liferay-portal-sample.git
              cd ~/liferay-portal-sample/configs/prod
              docker compose up -d;
            fi
