services:
  portal:
    image: ghcr.io/codeboychik/liferay-portal-sample:${RELEASE_TAG:-master}
    ports:
      - "8080:8080"
    volumes:
      - ./portal-ext.properties:/mnt/liferay/files/portal-ext.properties
      - ./setenv.sh:/mnt/liferay/files/tomcat/bin/setenv.sh
      - ./osgi/configs/com.liferay.portal.search.elasticsearch.configuration.ElasticsearchConfiguration.config:/mnt/liferay/files/osgi/configs/com.liferay.portal.search.elasticsearch.configuration.ElasticsearchConfiguration.config