#
# MySQL
#
#jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
#jdbc.default.url=jdbc:mysql://prod.server/lportalprod
#jdbc.default.username=root
#jdbc.default.password=

virtual.hosts.valid.hosts=10.8.0.1